### ISSUE TITLE
Doesn't install without gdebi on Ubuntu 20.10 (arm64)

### ISSUE THREAD

**Issue by ghost** [Itai-Nelken/Etcher-arm-32-64#2]
Doesn't install properly on Ubuntu 20.10 (arm64)

dpkg-deb: error: './balena-etcher-1.5.109_arm64.deb' is not a Debian format archive
dpkg: error processing archive ./balena-etcher-1.5.109_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./balena-etcher-1.5.109_arm64.deb

**Comment by Itai-Nelken** [comment]
@boomerangos weird, maybe try compiling yourself, I added the link to futurejones build instructions to the [readme](https://github.com/Itai-Nelken/Etcher-arm-32-64#compile).
I'll look it up tomorrow as I don't have my pi with me right now.

**Comment by Itai-Nelken** [comment]
try downloading the arm64 .deb, opening terminal in the directory where it is and type: `sudo dpkg -y balena-etcher-1.5.109_arm64.deb`, the type: `sudo apt --fix-broken install` and then `sudo dpkg -y balena-etcher-1.5.109_arm64.deb` again.
It might work, if it does, tell me and I'll update the install script

**Comment by Itai-Nelken** [comment]
@boomerangos good news! I compiled etcher again and it works great on ubuntu 20.10

**Comment by Itai-Nelken** [comment]
@boomerangos the updated 64bit installer is on pi-apps, update pi-apps and it should work now!
