### ISSUE TITLE
[Feature Request] Add balena-etcher-electron to your apt repo

### ISSUE THREAD

**Issue by Jai-JAP** [Itai-Nelken/Etcher-arm-32-64#4]

**Comment by Itai-Nelken** [comment]
which apt repo? the webcord one?

**Comment by Itai-Nelken** [comment]
also its already in @chunky-milk's apt repo: https://chunky-milk.github.io/raspbian-addons/

**Comment by Jai-JAP** [comment]
Thanks for your response

**Comment by Jai-JAP** [comment]
> also its already in @chunky-milk's apt repo: https://chunky-milk.github.io/raspbian-addons/

Closing this issue as I found the solution. Thanks again.

**Comment by Itai-Nelken** [comment]
You are welcome!
