### ISSUE TITLE
screen flashes white whenever i try to flash

### ISSUE THREAD

**Issue by confuzled** [Itai-Nelken/Etcher-arm-32-64#5]
the aplication turns white whenever i try to flash my sd card

**Comment by Itai-Nelken** [comment]
what version are you using?

**Comment by confuzled** [comment]
whatever the latest version on pi apps is

**Comment by Itai-Nelken** [comment]
Try the latest release: https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/tag/v1.5.120
It isn't in pi-apps yet.

**Comment by confuzled** [comment]
ok

**Comment by Itai-Nelken** [comment]
Does it work?

**Comment by confuzled** [comment]
sorry im on my laptop atm and i will be on my raspi in a couple hours

**Comment by ryanfortner** [comment]
@donnerkebab1730 are you having this error when trying to flash an .xz file? I'm also having that issue, along with [several other users](https://github.com/balena-io/etcher/issues/3558)

**Comment by confuzled** [comment]
> @donnerkebab1730 are you having this error when trying to flash an .xz file? I'm also having that issue, along with [several other users](https://github.com/balena-io/etcher/issues/3558)

Any file type, completely forget about this lol

**Comment by ryanfortner** [comment]
Try out the newest release (1.5.121)

**Comment by confuzled** [comment]
Will do when I get a chance

**Comment by ryanfortner** [comment]
v1.7.0 has been released: https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/tag/v1.7.0, are you still encountering this problem?

If not, this issue can be closed

**Comment by confuzled** [comment]
Completely forgot about this as I did the thing on another computer. Closed
