### ISSUE TITLE
Please add `--disable-seccomp-filter-sandbox`

### ISSUE THREAD

**Issue by Botspot** [Itai-Nelken/Etcher-arm-32-64#6]
Please change your debs to add the `--disable-seccomp-filter-sandbox` flag to the .desktop file.

**Comment by ryanfortner** [comment]
I'll rebuild the debs in a few minutes. I will be opening a PR on the pi-apps-coders/files repo to add the files.

**Comment by Itai-Nelken** [comment]
@ryanfortner thanks!

**Comment by ryanfortner** [comment]
repacked and uploaded. please merge https://github.com/Pi-Apps-Coders/files/pull/31, then I can make the changes to pi-apps scripts
